services:

  mysql:
    image: mysql:8.0
    container_name: product-mysql
    environment:
      MYSQL_ROOT_PASSWORD: 9661
      MYSQL_DATABASE: productmanagement
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  app:
    build: .
    container_name: product-app
    depends_on:
      - mysql
    ports:
      - "8000:8000"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/productmanagement
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: 9661

volumes:
  mysql_data: